#c.bindings.default = {}
c.auto_save.session = True
c.scrolling.smooth = True

config.unbind('b')
config.unbind('PP')
config.unbind('pp')
config.unbind('D')
config.unbind('m')
config.unbind('M')
config.unbind('j')
config.unbind('k')
config.unbind('f')
config.unbind('F')

config.bind('pP', 'open -t -- {primary}')
config.bind('pp', 'open -t -- {clipboard}')
config.bind('PP', 'open -- {clipboard}')
config.bind('Pp', 'open -- {clipboard}')
config.bind('D', 'quit --save')
config.bind('m', 'bookmark-add')
config.bind('M', 'set-mark')
config.bind('sh', 'open -t qute://history/')
config.bind('th', 'open -t https://bbs.hupu.com/all-nba')
#config.bind('j', 'run-with-count 50 scroll down')
#config.bind('k', 'run-with-count 50 scroll up')
config.bind('j', 'scroll-px 0 100')
config.bind('k', 'scroll-px 0 -100')
config.bind('gl', 'tab-move +')
config.bind('gh', 'tab-move -')
#config.bind("tt", "set-cmd-text -s :open -t")
config.bind("tt", "set-cmd-text -s :open -b")
config.bind('b', 'set-cmd-text -s :tab-select')
config.bind('h', 'tab-prev')
config.bind('l', 'tab-next')
config.bind('f', 'hint all tab')
config.bind('F', 'hint all tab-fg')
config.load_autoconfig()
